name: generate-website

on:
  workflow_run:
    workflows: ["generate-documentation"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'
  
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
  
      - name: Generate Documentation
        run: |
          sphinx-apidoc -o docs/source/ src/
          cd docs
          make html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/build/html/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
