

def generate_fuv(pum, puv):
    """
    The Final Unlock Vector is a 15-element vector, generated by the Preliminary Unlocking Matrix (PUM) and the Preliminary Unlocking Vector (PUV).
    The vector has one entry FUV[i] per LIC, which is always set to true if PUV[i] is set to false. Otherwise, it is set to true only if all the elements in the row i of PUM are true.

    :param pum: Preliminary Unlocking Matrix.
    :type pum: list[list[bool]]

    :param puv: Preliminary Unlocking Vector.
    :type puv: list[bool]

    :return: A 15-element vector containing boolean expressions.
    :rtype: list[bool]
    """
    fuv = [False]*len(puv)

    for i in range(len(puv)):
        true_or_not = not puv[i] or all(pum[i])
        fuv[i] = true_or_not
    return fuv
